const resData = [
    {
        "distance": 2.18,
        "name": "Wok Of Life",
        "location": "Kalina",
        "slug": "wok-of-life-kalina",
        "restaurant_active": 1,
        "restaurant_has_pre_order": 0,
        "available_cuisines": "Asian, Chinese",
        "logo_url": "https://cdn.thrivenow.in/consumer-app/Cuisines/Asian/6.png",
        "city": "Mumbai",
        "pincode": "400029",
        "available_offers": 0,
        "free_delivery_available": false,
        "offer_display_title": null,
        "estimated_delivery_time": 30,
        "rating": 4.4,
        "next_open_time": null
        },
        {
        "distance": 2.24,
        "name": "Chandni Chowk Bhaturewale",
        "location": "Kalina, Santacruz East",
        "slug": "chandni-chowk-bhaturewale-santa-cruz",
        "restaurant_active": 1,
        "restaurant_has_pre_order": 0,
        "available_cuisines": "North Indian",
        "logo_url": "https://cdn.thrivenow.in/consumer-app/Cuisines/Indian/8.png",
        "city": "Mumbai",
        "pincode": "400098",
        "available_offers": 0,
        "free_delivery_available": false,
        "offer_display_title": null,
        "estimated_delivery_time": 30,
        "rating": 4.0,
        "next_open_time": null
        },
        {
        "distance": 5.89,
        "name": "Domino's Pizza",
        "location": "Andheri - Kurla Road",
        "slug": "domino-s-pizza-andheri-kurla-road",  
        "restaurant_active": 1,
        "restaurant_has_pre_order": 0,
        "available_cuisines": "Desserts, Fast Food, Italian, Pasta, Pizza",
        "logo_url": "https://cdn.thrivenow.in/consumer-app/Cuisines/Pizza/5.png",
        "city": "Mumbai",
        "pincode": "400072",
        "available_offers": 0,
        "free_delivery_available": false,
        "offer_display_title": null,
        "estimated_delivery_time": 55,
        "rating": 3.2,
        "next_open_time": null
        },
        {
        "distance": 2.33,
        "name": "Charcoal Eats - Biryani & Beyond",
        "location": "KALINA",
        "slug": "charcoal-eats-biryani-beyond-kalina",
        "restaurant_active": 1,
        "restaurant_has_pre_order": 0,
        "available_cuisines": "North Indian",
        "logo_url": "https://cdn.thrivenow.in/images/100236/28306-Charcoal_Eats__Biryani__Beyond-thrive-background-image.jpeg?1679475881",
        "city": "Mumbai",
        "pincode": "400098",
        "available_offers": 0,
        "free_delivery_available": false,
        "offer_display_title": null,
        "estimated_delivery_time": 30,
        "rating": 3.9,
        "next_open_time": null
        },
        {
        "distance": 4.52,
        "name": "Domino's Pizza",
        "location": "Sion - Trombay Road",
        "slug": "domino-s-pizza-sion-trombay-road-81b97366-e62e-4d95-a859-a4629308b9f7",
        "restaurant_active": 1,
        "restaurant_has_pre_order": 0,
        "available_cuisines": "Desserts, Fast Food, Italian, Pasta, Pizza",
        "logo_url": "https://cdn.thrivenow.in/consumer-app/Cuisines/Pizza/6.png",
        "city": "Mumbai",
        "pincode": "400071",
        "available_offers": 0,
        "free_delivery_available": false,
        "offer_display_title": null,
        "estimated_delivery_time": 45,
        "rating": 3.6,
        "next_open_time": null
        },
        {
        "distance": 2.62,
        "name": "Brijwasi Sweets",
        "location": "Bandra Kurla Complex",
        "slug": "brijwasi-sweets-bandra-kurla-complex",
        "restaurant_active": 1,
        "restaurant_has_pre_order": 0,
        "available_cuisines": "Indian Sweets, Savouries, Snacks",
        "logo_url": "https://cdn.thrivenow.in/images/133849/Hero_Image_4_3.jpg?1695049099",
        "city": "Mumbai",
        "pincode": "400071",
        "available_offers": 0,
        "free_delivery_available": false,
        "offer_display_title": null,
        "estimated_delivery_time": 35,
        "rating": 3.8,
        "next_open_time": null
        },
        {
        "distance": 5.17,
        "name": "Tibb’s Frankie - Serving Rolls Since 1969",
        "location": "Chembur ( E )",
        "slug": "tibb-s-frankie-serving-rolls-since-1969-chembur-e",
        "restaurant_active": 1,
        "restaurant_has_pre_order": 0,
        "available_cuisines": "North Indian, Rolls",
        "logo_url": "https://cdn.thrivenow.in/images/163298/Chipotle.jpg?1698840719",
        "city": "Mumbai",
        "pincode": "400071",
        "available_offers": 0,
        "free_delivery_available": false,
        "offer_display_title": null,
        "estimated_delivery_time": 50,
        "rating": 3,
        "next_open_time": null
        },
        {
        "distance": 2.92,
        "name": "Meat Culture",
        "location": "Milan Nagar, Kurla",
        "slug": "meat-culture-kurla",
        "restaurant_active": 1,
        "restaurant_has_pre_order": 0,
        "available_cuisines": "Fresh Meat",
        "logo_url": "https://cdn.thrivenow.in/merchants/background_images/000/013/829/original/781.png?1659018699",
        "city": "Mumbai",
        "pincode": "400024",
        "available_offers": 0,
        "free_delivery_available": false,
        "offer_display_title": null,
        "estimated_delivery_time": 35,
        "rating": 4.4,
        "next_open_time": null
        },
        {
        "distance": 6.5,
        "name": "Domino's Pizza",
        "location": "BS Devashi Marg",
        "slug": "domino-s-pizza-bs-devashi-marg",
        "restaurant_active": 1,
        "restaurant_has_pre_order": 0,
        "available_cuisines": "Desserts, Fast Food, Italian, Pasta, Pizza",
        "logo_url": "https://cdn.thrivenow.in/consumer-app/Cuisines/Pizza/8.png",
        "city": "Mumbai",
        "pincode": "400088",
        "available_offers": 0,
        "free_delivery_available": false,
        "offer_display_title": null,
        "estimated_delivery_time": 55,
        "rating": 4.4,
        "next_open_time": null
        },
        {
        "distance": 3.37,
        "name": "Haribhai Damodar Mithaiwala",
        "location": "Tilak Nagar, Chembur",
        "slug": "haribhaidamodarmithaiwala",
        "restaurant_active": 1,
        "restaurant_has_pre_order": 0,
        "available_cuisines": "Dairy, Desserts and bakes, Fast Food, Finger Food, Gujarati, Home Food, Mithai, Samosa, Snacks, Street Food, Sweets",
        "logo_url": "https://cdn.thrivenow.in/merchants/background_images/000/026/402/original/data?1669441817",
        "city": "Mumbai",
        "pincode": "400089",
        "available_offers": 0,
        "free_delivery_available": false,
        "offer_display_title": null,
        "estimated_delivery_time": 40,
        "rating": 4.4,
        "next_open_time": null
        },
        {
        "distance": 4.68,
        "name": "Domino's Pizza",
        "location": "Ramnarayan Narkar Marg",
        "slug": "domino-s-pizza-ramnarayan-narkar-marg",
        "restaurant_active": 1,
        "restaurant_has_pre_order": 0,
        "available_cuisines": "Desserts, Fast Food, Italian, Pasta, Pizza",
        "logo_url": "https://cdn.thrivenow.in/consumer-app/Cuisines/Pizza/4.png",
        "city": "Mumbai",
        "pincode": "400077",
        "available_offers": 0,
        "free_delivery_available": false,
        "offer_display_title": null,
        "estimated_delivery_time": 45,
        "rating": 3.5,
        "next_open_time": null
        },
        {
        "distance": 3.51,
        "name": "Meat Culture",
        "location": "sakinaka",
        "slug": "meat-culture-sakinaka",
        "restaurant_active": 1,
        "restaurant_has_pre_order": 0,
        "available_cuisines": "Fresh Meat",
        "logo_url": "https://cdn.thrivenow.in/merchants/background_images/000/013/831/original/781.png?1659018702",
        "city": "Mumbai",
        "pincode": "400072",
        "available_offers": 0,
        "free_delivery_available": false,
        "offer_display_title": null,
        "estimated_delivery_time": 40,
        "rating": 4.4,
        "next_open_time": null
        }
]

export default resData